version: "3.9"

services:
  database:
    image: postgres
    container_name: database_menotoi
    restart: always
    ports:
      - 43012:5432
    environment:
      - POSTGRES_USER=DOCKER
      - POSTGRES_PASSWORD=5432
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
